language: c++

sudo: required

compiler:
  - gcc
os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

  #Codecov
  - sudo pip install codecov
  - chmod +x .get_code_cov.sh

  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install:
  #Install Eigen
  - sudo apt-get install libeigen3-dev
  - sudo ln -s /usr/include/eigen3/Eigen /usr/local/include/Eigen

  #Install libconfig
  - sudo apt-get install libconfig++-dev

  #Install openMPI
  - sudo apt-get install openmpi-bin
  - sudo apt-get install libopenmpi-dev
  
  #Codecov
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

script:
  - mpic++ --showme
  - mpic++ --version
  #Compile without optimization and with coverage
  - make test
  #Run the program
  - mpirun -n 1 /bin/DaMaSCUS-Simulator bin/.test.cfg
  - mpirun -n 1 /bin/DaMaSCUS-Analyzer Test
  #Codecov
  - ./.get_code_cov.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"