language: c++
sudo: false

compiler:
  - gcc
  - clang

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

  - sudo apt-get -qq update

install:
  - sudo apt-get install libeigen3-dev
  - sudo apt-get install libconfig++-dev
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
script:
  - make
  - cd bin/
  - mpirun -n 2 DaMaSCUS-Simulator DaMaSCUS.cfg
  - mpirun -n 2 DaMaSCUS-Analyzer exampleID

after_success: 
  - bash <(curl -s https://codecov.io/bash)